name: Danger2
on:
  pull_request:
    paths:
      - ".swiftlint.yml"
      - "**/*.swift"
jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9 # Look at the `Note for version`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
